services:
  stocklerts:
    container_name: stocklerts-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/code/stocklerts:/stocklerts
    environment:
      FINNHUB_API_KEY: "${FINNHUB_API_KEY}"
      ENCRYPT_KEY: "${ENCRYPT_KEY}"
    restart: unless-stopped

  webhook-handler:
    container_name: stocklerts-webhook-handler
    build:
      context: .
      dockerfile: Dockerfile.webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/code/stocklerts:/stocklerts
    environment:
      - GH_WEBHOOK_SECRET=${GH_WEBHOOK_SECRET}
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
    ports:
      - "5001:5000"
    networks:
      - app-network

  ngrok:
    container_name: stocklerts-ngrok
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http --domain=usable-perch-smoothly.ngrok-free.app webhook-handler:5000
    depends_on:
      - webhook-handler
    networks:
      - app-network

networks:
  app-network:
    driver: bridge