services:
  stocklerts:
    container_name: stocklerts-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      FINNHUB_API_KEY: "${FINNHUB_API_KEY}"
      ENCRYPT_KEY: "${ENCRYPT_KEY}"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
