defaults:
  cooldown_period_minutes: 60
  max_notifications_per_day: 100
  max_quote_calls_per_min: 60

heartbeat:
  url: https://uptime.betterstack.com/api/v1/heartbeat/E6cwqjfF4G7ZzgzFzNo2Uku2

alertzy:
  accounts:
    - user_id: 1
      account_id: 18tu6LkU4y9uNArpNlAyog==
      notify_thresh: 1
      is_admin: true

    - user_id: 2
      account_id: Z1oUopdYIIxdgdE0F1O2NA==
      notify_thresh: 1

    - user_id: 3
      account_id: yCFNLiNEYZ5m/rgIjjFYjA==
      notify_thresh: 1

tickers:
  # Technology & Internet
  - symbol: AAPL
    threshold:
      - value: 1
        users:
        - 1
        - 2
        - 3

  - symbol: BABA
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: ABNB
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: BMBL
    threshold:
      - value: 1
        users:
        - 1
        - 2
        - 3

  - symbol: DASH
    threshold:
      - value: -2
        users:
        - 1
        - 2
        - 3

  - symbol: RDDT
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Semiconductors & AI Hardware
  - symbol: AMD
    threshold:
      - value: 1
        users:
        - 1
        - 2
        - 3

  - symbol: NVDA
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: QCOM
    threshold:
      - value: -2
        users:
        - 1
        - 2
        - 3

  - symbol: TSM
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Software & Cybersecurity
  - symbol: PLTR
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: CRWD
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Fintech & Crypto
  - symbol: SOFI
    threshold:
      - value: 1
        users:
        - 1
        - 2
        - 3

  - symbol: CRCL
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: MSTR
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Energy & Utilities
  - symbol: CEG
    threshold:
      - value: -2
        users:
        - 1
        - 2
        - 3

  - symbol: PCG
    threshold:
      - value: -2
        users:
        - 1
        - 2
        - 3

  - symbol: TRP
    threshold:
      - value: -3
        users:
        - 1
        - 2
        - 3

  - symbol: OKLO
    threshold:
      - value: -2
        users:
        - 1
        - 2
        - 3

  - symbol: NEE   # NextEra Energy (Renewables)
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: FSLR  # First Solar (Solar Energy)
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Electric Vehicles & Clean Tech
  - symbol: TSLA
    threshold:
      - value: -2
        users:
        - 1
        - 2
        - 3

  # Quantum Computing
  - symbol: IONQ  # IonQ Inc.
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: RGTI  # Rigetti Computing
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Gene Editing & Biotech
  - symbol: CRSP  # CRISPR Therapeutics
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: NTLA  # Intellia Therapeutics
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  - symbol: BEAM  # Beam Therapeutics
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3

  # Consumer & Retail
  - symbol: COST
    threshold:
      - value: 1
        users:
        - 1
        - 2
        - 3

  - symbol: GAP
    threshold:
      - value: 1
        users:
        - 1
        - 2
        - 3

  # Index / ETF
  - symbol: VOO
    threshold:
      - value: -1
        users:
        - 1
        - 2
        - 3