defaults:
  cooldown_period_minutes: 60
  max_notifications_per_day: 100
  max_quote_calls_per_min: 60

alertzy:
  accounts:
    - user_id: 1
      account_id: 18tu6LkU4y9uNArpNlAyog==
      notify_thresh: 1

    - user_id: 3
      account_id: yCFNLiNEYZ5m/rgIjjFYjA==
      notify_thresh: 1

tickers:
  - symbol: AAPL
    threshold:
        - value: -4
          users:
            - 1
            - 3

  - symbol: MSFT
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: NVDA
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: GOOGL
    threshold:
      - value: -4
        users:
          - 1

  - symbol: GAP
    threshold:
      - value: 10
        users:
          - 1

  - symbol: META
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: TSLA
    threshold:
      - value: -10
        users:
          - 1
          - 3

  - symbol: BMBL
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: COST
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: PCG
    threshold:
      - value: -4
        users:
          - 1
          - 3
          
  - symbol: TSM
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: QCOM
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: ABNB
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: AMD
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: RDDT
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: PLTR
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: CRWD
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: MDB
    threshold:
      - value: -4
        users:
          - 1
          - 3

  - symbol: DASH
    threshold:
      - value: -4
        users:
          - 1
          - 3
