defaults:
  cooldown_period_minutes: 60
  max_notifications_per_day: 100
  max_quote_calls_per_min: 60

alertzy:
  accounts:
    - user_id: 1
      account_id: 18tu6LkU4y9uNArpNlAyog==

    - user_id: 2
      account_id: 18tu6LkU4y9uNArpNlAyog==

tickers:
  - symbol: AAPL
    threshold:
        - value: -4.5
          users:
            - 1

  - symbol: MSFT
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: GOOGL
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: GAP
    threshold:
      - value: 5
        users:
          - 1

  - symbol: META
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: TSLA
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: BMBL
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: COST
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: PCG
    threshold:
      - value: -4.5
        users:
          - 1

  - symbol: TSM
    threshold:
      - value: -4.5
        users:
          - 1
