defaults:
  cooldown_period_minutes: 60
  max_notifications_per_day: 100
  max_quote_calls_per_min: 60

alertzy:
  accounts:
    - user_id: 1
      account_id: 18tu6LkU4y9uNArpNlAyog==

    - user_id: 2
      account_id: 18tu6LkU4y9uNArpNlAyog==

    - user_id: 3
      account_id: yCFNLiNEYZ5m/rgIjjFYjA==

tickers:
  - symbol: AAPL
    threshold:
        - value: 5
          users:
            - 1
        - value: 0
          users:
            - 2
            - 3

  - symbol: MSFT
    threshold:
      - value: 5
        users:
          - 1
          - 3

  - symbol: NVDA
    threshold:
      - value: 5
        users:
          - 3

  - symbol: GOOGL
    threshold:
      - value: -0.3
        users:
          - 1

  - symbol: GAP
    threshold:
      - value: 0
        users:
          - 1

