defaults:
  cooldown_period_minutes: 60
  max_notifications_per_day: 100
  max_quote_calls_per_min: 60

heartbeat:
  url: https://uptime.betterstack.com/api/v1/heartbeat/E6cwqjfF4G7ZzgzFzNo2Uku2

alertzy:
  accounts:
    - user_id: 1
      account_id: 18tu6LkU4y9uNArpNlAyog==
      notify_thresh: 1

    - user_id: 3
      account_id: yCFNLiNEYZ5m/rgIjjFYjA==
      notify_thresh: 1

tickers:
  - symbol: AAPL
    threshold:
        - value: 1
          users:
            - 1
            - 3

  - symbol: MSFT
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: NVDA
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: GOOGL
    threshold:
      - value: -2
        users:
          - 1

  - symbol: GAP
    threshold:
      - value: 3
        users:
          - 1

  - symbol: META
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: TSLA
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: BMBL
    threshold:
      - value: -3
        users:
          - 1

  - symbol: COST
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: PCG
    threshold:
      - value: -2
        users:
          - 1
          - 3
          
  - symbol: TSM
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: QCOM
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: ABNB
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: AMD
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: RDDT
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: PLTR
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: CRWD
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: MDB
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: DASH
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: OKLO
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: CEG
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: VOO
    threshold:
      - value: -2
        users:
          - 1
          - 3

  - symbol: HD
    threshold:
      - value: -2
        users:
          - 1
          - 3
          
  - symbol: AI
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: BE
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: TRP
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: GETY
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: PERF
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: BBAI
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: ADBE
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: GRND
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: MSTR
    threshold:
      - value: -3
        users:
          - 1
          - 3

  - symbol: COST
    threshold:
      - value: 1
        users:
          - 1
          - 3

  - symbol: CRCL
    threshold:
      - value: 1
        users:
          - 3
