FROM python:3.11-slim

WORKDIR /stocklerts

# Install Git and build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        git \
        build-essential \
        libyaml-dev \
        python3-dev \
        libffi-dev \
        libssl-dev \
        && rm -rf /var/lib/apt/lists/*

# Upgrade pip to the latest version
RUN pip install --upgrade pip

# Install Docker SDK and Python dependencies
COPY webhook_handler_reqs.txt .
RUN pip install --no-cache-dir -r webhook_handler_reqs.txt

# Install Docker SDK
RUN pip install --no-cache-dir docker

# Copy the rest of the application code
COPY . .

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "webhook_handler:app"]